--Nome: Caike Dametto RM: 558614
--Nome: Guilhetme Janunzzi RM: 558461

CREATE TABLE T_EH_USUARIO (
    CD_USUARIO            NUMBER(8) NOT NULL,
    NM_USUARIO            VARCHAR2(200) NOT NULL,
    DS_EMAIL	          VARCHAR2(150) NOT NULL,
    DS_SENHA              VARCHAR2(255) NOT NULL,
    DS_TELEFONE           VARCHAR2(20),
    DS_TIPO               VARCHAR2(20) NOT NULL,
    DT_REGISTRO           DATE NOT NULL,
    DS_STATUS             NUMBER(1) NOT NULL
);

ALTER TABLE T_EH_USUARIO ADD CONSTRAINT PK_EH_USUARIO PRIMARY KEY ( cd_usuario );
ALTER TABLE T_EH_USUARIO ADD CONSTRAINT UK_EH_USUARIO_EMAIL UNIQUE (DS_EMAIL);

CREATE TABLE T_EH_PEDIDO_AJUDA (
    CD_PEDIDO             NUMBER(8) NOT NULL,
    CD_USUARIO            NUMBER(8) NOT NULL,
    DS_TIPO               VARCHAR2(100) NOT NULL,
    DS_DESCRICAO          VARCHAR2(1000) NOT NULL,
    DS_LATITUDE           NUMBER(10,7) NOT NULL,
    DS_LONGITUDE          NUMBER(10,7) NOT NULL,
    DS_ENDERECO           VARCHAR2(300),
    DT_PEDIDO             DATE NOT NULL,
    DS_STATUS             VARCHAR2(20) NOT NULL
);

ALTER TABLE T_EH_PEDIDO_AJUDA ADD CONSTRAINT PK_EH_PEDIDO_AJUDA PRIMARY KEY ( cd_pedido );
ALTER TABLE T_EH_PEDIDO_AJUDA ADD CONSTRAINT FK_EH_CD_SOLICITANTE FOREIGN KEY ( cd_usuario ) REFERENCES T_EH_USUARIO ( cd_usuario );

CREATE TABLE T_EH_ATENDIMENTO_VOLUNTARIO (
    CD_ATENDIMENTO        NUMBER(8) NOT NULL,
    CD_PEDIDO             NUMBER(8) NOT NULL,
    CD_USUARIO            NUMBER(8) NOT NULL,
    DT_MOMENTO_ACEITE     DATE NOT NULL,
    DT_MOMENTO_CONCLUSAO  DATE,
    DS_OBSERVACOES        VARCHAR2(500)
);

ALTER TABLE T_EH_ATENDIMENTO_VOLUNTARIO ADD CONSTRAINT PK_EH_CD_ATENDIMENTO PRIMARY KEY ( cd_atendimento );
ALTER TABLE T_EH_ATENDIMENTO_VOLUNTARIO ADD CONSTRAINT FK_EH_CD_PEDIDO FOREIGN KEY ( cd_pedido ) REFERENCES T_EH_PEDIDO_AJUDA ( cd_pedido );
ALTER TABLE T_EH_ATENDIMENTO_VOLUNTARIO ADD CONSTRAINT FK_EH_CD_VOLUNTARIO FOREIGN KEY ( cd_usuario ) REFERENCES T_EH_USUARIO ( cd_usuario );

CREATE TABLE T_EH_ALERTA (
   CD_ALERTA              NUMBER(8) NOT NULL,
   DS_TITULO              VARCHAR2(150) NOT NULL,
   DS_MENSAGEM            VARCHAR2(2000) NOT NULL,
   DT_PUBLICACAO          DATE NOT NULL,
   DS_SERIEDADE           VARCHAR2(50) NOT NULL,
   DS_FONTE               VARCHAR2(100),
   DS_ATIVO               NUMBER(1) NOT NULL
);

ALTER TABLE T_EH_ALERTA ADD CONSTRAINT PK_EH_ALERTA PRIMARY KEY ( cd_alerta );


CREATE TABLE T_EH_DICA_PREPARACAO (
   CD_DICA                NUMBER(8) NOT NULL,
   DS_TITULO              VARCHAR2(150) NOT NULL,
   DS_CONTEUDO            CLOB NOT NULL,
   DS_CATEGORIA           VARCHAR2(50) NOT NULL,
   DT_ULTIMA_ATUALIZACAO  DATE NOT NULL
);

ALTER TABLE T_EH_DICA_PREPARACAO ADD CONSTRAINT PK_EH_DICA_PREPARACAO PRIMARY KEY ( cd_dica );


CREATE SEQUENCE SEQ_EH_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EH_PEDIDO_AJUDA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EH_ATENDIMENTO_VOLUNTARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EH_ALERTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EH_DICA_PREPARACAO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;