--Nome: Caike Dametto RM: 558614
--Nome: Guilhetme Janunzzi RM: 558461

DROP TABLE T_EH_USUARIO CASCADE CONSTRAINTS;

DROP TABLE T_EH_PEDIDO_AJUDA CASCADE CONSTRAINTS;

DROP TABLE T_EH_ATENDIMENTO_VOLUNTARIO CASCADE CONSTRAINTS;

DROP TABLE T_EH_ALERTA CASCADE CONSTRAINTS;

DROP TABLE T_EH_DICA_PREPARACAO CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_EH_USUARIO;
DROP SEQUENCE SEQ_EH_PEDIDO_AJUDA;
DROP SEQUENCE SEQ_EH_ATENDIMENTO_VOLUNTARIO;
DROP SEQUENCE SEQ_EH_ALERTA;
DROP SEQUENCE SEQ_EH_DICA_PREPARACAO;